title: Wentao-Liao‘s Homepage
page-top-title: Wentao-Liao
top-section-bg-text: Be what you wanna be
home-subtitle: Yourname&ensp;|&ensp;Wentao-Liao
copyright-text: '&copy; Wentao-Liao 2023-2025. All Rights Reserved.'
